--1
DECLARE @SUBJECT_NAME VARCHAR(100);
DECLARE @SUBJECT_LIST VARCHAR(MAX) = '';

DECLARE SUBJECT_CURSOR CURSOR FOR 
    SELECT SUBJECT_NAME 
    FROM SUBJECT 
    WHERE PULPIT = '»—Ë“';

OPEN SUBJECT_CURSOR;
FETCH FROM SUBJECT_CURSOR INTO @SUBJECT_NAME;
PRINT '—œ»—Œ  ƒ»—÷»œÀ»Õ Õ¿  ¿‘≈ƒ–≈ »—Ë“:';

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @SUBJECT_LIST = @SUBJECT_LIST + RTRIM(@SUBJECT_NAME) + ', ';
    FETCH FROM SUBJECT_CURSOR INTO @SUBJECT_NAME;
END

CLOSE SUBJECT_CURSOR;
DEALLOCATE SUBJECT_CURSOR;
PRINT @SUBJECT_LIST;
GO

--2
DECLARE TEACHERCURSOR CURSOR LOCAL 
    FOR SELECT TEACHER_NAME, GENDER 
    FROM TEACHER;

DECLARE @NAME NVARCHAR(100), @GENDER CHAR(1);
OPEN TEACHERCURSOR;
FETCH FROM TEACHERCURSOR INTO @NAME, @GENDER;
PRINT '1. ' + @NAME + ' (' + @GENDER + ')';
GO
DECLARE @NAME NVARCHAR(100), @GENDER CHAR(1);
FETCH FROM TEACHERCURSOR INTO @NAME, @GENDER;
PRINT '2. ' + @NAME + ' (' + @GENDER + ')';
GO

DECLARE TEACHERCURSOR2 CURSOR 
    FOR SELECT TEACHER_NAME, GENDER 
    FROM TEACHER;

DECLARE @NAME NVARCHAR(100), @GENDER CHAR(1);
OPEN TEACHERCURSOR2;
FETCH FROM TEACHERCURSOR2 INTO @NAME, @GENDER;
PRINT '1. ' + @NAME + ' (' + @GENDER + ')';
GO

DECLARE @NAME NVARCHAR(100), @GENDER CHAR(1);
FETCH FROM TEACHERCURSOR2 INTO @NAME, @GENDER;
PRINT '2. ' + @NAME + ' (' + @GENDER + ')';
CLOSE TEACHERCURSOR2;
DEALLOCATE TEACHERCURSOR2;
GO

--3
DECLARE @NAME NVARCHAR(100), @GENDER CHAR(1);
DECLARE STATIC_CURSOR CURSOR STATIC 
    FOR SELECT TEACHER_NAME, GENDER 
    FROM TEACHER;

OPEN STATIC_CURSOR;
FETCH FROM STATIC_CURSOR INTO @NAME, @GENDER;
PRINT '1. ' + @NAME + ' (' + @GENDER + ')';
UPDATE TEACHER SET GENDER = 'Ê' WHERE TEACHER_NAME = @name;
--UPDATE TEACHER SET GENDER = 'Ï' WHERE TEACHER_NAME = @name;
FETCH FROM STATIC_CURSOR INTO @NAME, @GENDER;
PRINT '2. ' + @NAME + ' (' + @GENDER + ')';

CLOSE STATIC_CURSOR;
DEALLOCATE STATIC_CURSOR;
GO

DECLARE GROUPS CURSOR LOCAL DYNAMIC 
    FOR SELECT P.PROFESSION_NAME  
    FROM dbo.PROFESSION P 
    WHERE P.FACULTY LIKE '»“';

DECLARE @RESULT VARCHAR(500) = '', @STROKE VARCHAR(60) = '';
OPEN GROUPS;
PRINT ' ŒÀ»◊≈—“¬Œ —“–Œ : ' + CAST(@@CURSOR_ROWS AS VARCHAR(5));

INSERT INTO PROFESSION
VALUES ('1', '»“', 'œŒÀ»√–¿‘»◊≈— Œ≈ Œ¡Œ–”ƒŒ¬¿Õ»≈ » —»—“≈Ã€ Œ¡–¿¡Œ“ » »Õ‘Œ–Ã¿÷»»', '»Õ∆≈Õ≈–-›À≈ “–ŒÃ≈’¿Õ» ');

FETCH GROUPS INTO @STROKE;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @RESULT = RTRIM(@STROKE) + ' , ' + @RESULT;
    FETCH GROUPS INTO @STROKE;
END;

PRINT(@RESULT);
CLOSE GROUPS;

DELETE FROM PROFESSION 
WHERE PROFESSION.PROFESSION LIKE '1';
GO

--4
DECLARE @ROW_NUM INT, @TEACHER_NAME NVARCHAR(100), @GENDER CHAR(1);

DECLARE TEACHERCURSOR CURSOR LOCAL STATIC SCROLL 
    FOR SELECT ROW_NUMBER() OVER (ORDER BY TEACHER_NAME) AS N, 
               TEACHER_NAME, GENDER 
    FROM TEACHER;

OPEN TEACHERCURSOR;

FETCH FIRST FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT 'œ≈–¬¿ﬂ —“–Œ ¿: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH NEXT FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT '—À≈ƒ”ﬁŸ¿ﬂ —“–Œ ¿: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH PRIOR FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT 'œ–≈ƒ€ƒ”Ÿ¿ﬂ —“–Œ ¿: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH LAST FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT 'œŒ—À≈ƒÕﬂﬂ —“–Œ ¿: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH ABSOLUTE -3 FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT '“–≈“‹ﬂ —“–Œ ¿ Œ“  ŒÕ÷¿: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH ABSOLUTE 5 FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT 'œﬂ“¿ﬂ —“–Œ ¿ Œ“ Õ¿◊¿À¿: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH RELATIVE 5 FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT 'Õ¿ 5 —“–Œ  ¬œ≈–≈ƒ: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

FETCH RELATIVE -5 FROM TEACHERCURSOR INTO @ROW_NUM, @TEACHER_NAME, @GENDER; 
PRINT 'Õ¿ 5 —“–Œ  Õ¿«¿ƒ: ' + CAST(@ROW_NUM AS VARCHAR(3)) + ' - ' + RTRIM(@TEACHER_NAME) + ' (' + @GENDER + ')';

CLOSE TEACHERCURSOR;
DEALLOCATE TEACHERCURSOR;

SELECT TEACHER_NAME FROM TEACHER;
GO

--5
CREATE TABLE #TEMPTTEACHER (
    TEACHER_NAME NVARCHAR(100),
    GENDER CHAR(1),
    PULPIT NVARCHAR(100)
);

INSERT INTO #TEMPTTEACHER (TEACHER_NAME, GENDER, PULPIT)
SELECT TEACHER_NAME, GENDER, PULPIT 
FROM TEACHER 
WHERE PULPIT = '»—Ë“';

SELECT * FROM #TEMPTTEACHER;

DECLARE @TEACHER_NAME NVARCHAR(100), @GENDER CHAR(1);
DECLARE TEACHER_CURSOR CURSOR FOR
SELECT TEACHER_NAME, GENDER 
FROM #TEMPTTEACHER 
WHERE PULPIT = '»—Ë“';

OPEN TEACHER_CURSOR;

FETCH FROM TEACHER_CURSOR INTO @TEACHER_NAME, @GENDER;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @GENDER = 'Ê'
    BEGIN
        UPDATE #TEMPTTEACHER 
        SET GENDER = 'Ï' 
        WHERE CURRENT OF TEACHER_CURSOR;
    END

    IF @TEACHER_NAME = '”·‡ÌÓ‚Ë˜ œ‡‚ÂÎ œ‡‚ÎÓ‚Ë˜'
    BEGIN
        DELETE FROM #TEMPTTEACHER 
        WHERE CURRENT OF TEACHER_CURSOR;
    END

    FETCH FROM TEACHER_CURSOR INTO @TEACHER_NAME, @GENDER;
END

CLOSE TEACHER_CURSOR;
DEALLOCATE TEACHER_CURSOR;

SELECT * FROM #TEMPTTEACHER;
DROP TABLE #TEMPTTEACHER;
GO

--6
SELECT PROGRESS.NOTE, STUDENT.IDSTUDENT 
FROM PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP;

DECLARE NOTE_CURSOR CURSOR FOR 
    SELECT PROGRESS.NOTE 
    FROM PROGRESS
    INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
    INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP 
    FOR UPDATE;

OPEN NOTE_CURSOR;
DECLARE @NOTE INT;
FETCH NOTE_CURSOR INTO @NOTE;
WHILE @@FETCH_STATUS = 0
BEGIN
    IF @NOTE < 4 
        DELETE FROM PROGRESS WHERE CURRENT OF NOTE_CURSOR;
	FETCH NOTE_CURSOR INTO @NOTE;
END
CLOSE NOTE_CURSOR;
GO

DECLARE @ID INT = 1002, @FETCHINGID INT;

DECLARE STUDENT_CURSOR CURSOR LOCAL FOR 
    SELECT IDSTUDENT FROM PROGRESS FOR UPDATE;

OPEN STUDENT_CURSOR;

FETCH STUDENT_CURSOR INTO @FETCHINGID;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @FETCHINGID = @ID
    BEGIN
        UPDATE PROGRESS 
        SET NOTE = NOTE + 1
        WHERE CURRENT OF STUDENT_CURSOR;
    END

    FETCH STUDENT_CURSOR INTO @FETCHINGID;
END
CLOSE STUDENT_CURSOR;

SELECT NOTE FROM PROGRESS
WHERE IDSTUDENT = 1002;
DEALLOCATE NOTE_CURSOR;