USE LAB6;
GO

/* 1 */
CREATE PROCEDURE PSUBJECT
AS
BEGIN
    DECLARE @a INT = (SELECT COUNT(*) FROM SUBJECT);
    SELECT SUBJECT, SUBJECT_NAME, PULPIT FROM SUBJECT;
    PRINT 'Количество записей в таблице: ' + CAST(@a AS NVARCHAR);
END;
GO
EXEC PSUBJECT;
DROP PROCEDURE PSUBJECT;

