use UNIVER;
--1
SELECT AT.AUDITORIUM_TYPENAME,
	MAX(AU.AUDITORIUM_CAPACITY) AS [максимум],
	MIN(AU.AUDITORIUM_CAPACITY) AS [минимум],
	AVG(AU.AUDITORIUM_CAPACITY) AS [среднее],
	SUM(AU.AUDITORIUM_CAPACITY) AS [сумма],
	COUNT(AU.AUDITORIUM) AS [кол-во]
FROM AUDITORIUM AU INNER JOIN AUDITORIUM_TYPE AT ON AU.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE
GROUP BY AT.AUDITORIUM_TYPENAME;

--2
SELECT NOTE AS [оценка],
	COUNT(*) AS [кол-во оценок]
FROM (SELECT NOTE,
		CASE 
			WHEN NOTE BETWEEN 1 AND 3 THEN '1-3'
			WHEN NOTE BETWEEN 4 AND 6 THEN '4-6'
			WHEN NOTE BETWEEN 7 AND 10 THEN '7-10'
            ELSE 'Другие'
		END AS G
		FROM PROGRESS) AS P
GROUP BY NOTE
ORDER BY NOTE DESC;

--3,4
SELECT F.FACULTY_NAME, G.PROFESSION, G.YEAR_FIRST,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(4,2)), 2) AS [средняя оценка]
FROM FACULTY F 
	INNER JOIN GROUPS G ON F.FACULTY = G.FACULTY
	INNER JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
	INNER JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
	--WHERE P.SUBJECT IN ('БД', 'ОАиП')
GROUP BY F.FACULTY_NAME, G.PROFESSION, G.YEAR_FIRST
ORDER BY [средняя оценка] DESC;

--5
SELECT G.PROFESSION, P.SUBJECT,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(4, 2)), 2) AS [средняя оценка]
FROM FACULTY F
	INNER JOIN GROUPS G ON F.FACULTY = G.FACULTY
	INNER JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
	INNER JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
WHERE F.FACULTY IN ('ИТ')
GROUP BY G.PROFESSION, P.SUBJECT;

--6
SELECT P.SUBJECT,
	COUNT(*) AS [количество студентов, получивших оценки 8 и 9]
FROM PROGRESS P
WHERE P.NOTE IN (8, 9)
GROUP BY P.SUBJECT
--HAVING COUNT(*) > 0
ORDER BY [количество студентов, получивших оценки 8 и 9] DESC;