use UNIVER;
--1
SELECT G.PROFESSION, S.SUBJECT_NAME,
	CAST(AVG(P.NOTE) AS DECIMAL(10, 2)) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ'
GROUP BY ROLLUP (G.PROFESSION, S.SUBJECT_NAME) 


SELECT G.PROFESSION, S.SUBJECT_NAME,
	CAST(AVG(P.NOTE) AS DECIMAL(10, 2)) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ'
GROUP BY G.PROFESSION, S.SUBJECT_NAME 
--2
SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ'
GROUP BY CUBE (G.PROFESSION, S.SUBJECT_NAME)
ORDER BY G.PROFESSION, S.SUBJECT_NAME;
	
--3
SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ'
GROUP BY G.PROFESSION, S.SUBJECT_NAME;

SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÕÒèÒ'
GROUP BY G.PROFESSION, S.SUBJECT_NAME;

SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ' 
GROUP BY G.PROFESSION, S.SUBJECT_NAME

UNION --ALL

SELECT  S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÕÒèÒ' 
GROUP BY  S.SUBJECT_NAME;

--4
SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ' 
GROUP BY G.PROFESSION, S.SUBJECT_NAME

INTERSECT

SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÕÒèÒ' 
GROUP BY G.PROFESSION, S.SUBJECT_NAME;

--5
SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÈÒ' 
GROUP BY G.PROFESSION, S.SUBJECT_NAME

EXCEPT

SELECT G.PROFESSION, S.SUBJECT_NAME,
	ROUND(CAST(AVG(P.NOTE) AS DECIMAL(10, 2)), 2) AS Average_Grade
FROM GROUPS G
INNER JOIN STUDENT ST ON G.IDGROUP = ST.IDGROUP
INNER JOIN PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
INNER JOIN SUBJECT S ON P.SUBJECT = S.SUBJECT
WHERE G.FACULTY = 'ÕÒèÒ' 
GROUP BY G.PROFESSION, S.SUBJECT_NAME;